#!/bin/bash
# Run Ruff for Python formatting and enforce no issues before commit

# Download Ruff configuration file from central location 
RUFF_CONFIG_FILE="$(git rev-parse --show-toplevel)/.ruff.toml"

# Run Ruff to fix issues
echo "Running Ruff on all python files ..."
ruff check . --config ${RUFF_CONFIG_FILE}

# Check if Ruff found any issues
if [ $? -ne 0 ]; then
  echo "Ruff found issues. Please fix them before committing."
  exit 1
else
  echo "Ruff passed. Proceeding with commit."
fi
