name: Pipeline [test -> build -> deploy]

on:
  push:
    branches-ignore:
      - 'dependabot/**'
      - 'main'

jobs:
  slsa:
    name: SLSA Supply Chain Security
    runs-on: ubuntu-latest
    steps:
      - name: SLSA Supply Chain Security
        uses: ministryofjustice/devsecops-actions/sca/slsa@559ec2408860d9237cc472a5710e61c1c2187ffa

  python_lint:
    name: python lint
    needs: 
      - slsa
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/test_python_lint.yml@v2 # WORKFLOW VERSION
    secrets: inherit

  pytest:
    name: pytest - ${{ matrix.test }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        test:
          - tests/clients/test_sharepoint.py
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Run pytest suite
        uses: ./.github/actions/run-pytest
        with:
          test-path: ${{ matrix.test }}
